### ISSUE TITLE
Add Login Delay

### ISSUE THREAD

**Issue by JRCrawford** [SenorKarlos/PGScout#29]
After the new proxy banning it would be wise if we had a "delay-login" feature that could be added to the config file.  It would work exactly the same way it does for the RocketMap config.

**Comment by darkelement1987** [comment]
lol i believe we already have this?

**Comment by whitewillem** [comment]
Uhm... we don't ?

**Comment by darkelement1987** [comment]
I know i del'd my comment lol

**Comment by JRCrawford** [comment]
For a general mr_mine config file is this ok?
`{
  "goman_proxy_support": false,
  "goman_hashing_rate_limit": "",
  "goman_hashing_max_rpm_count": "",
  "full_login_flow": true,
  "download_assets_and_items": false,
  "request_retry_delay": 5,
  "encounter_delay": 2.25,
  "debug_log": false,
  "log_file": "",
  "pgpool_update_interval": 120,
  "login_delay": 25
}`

If that actually does the trick I will close this issue as adding it is very simple.

**Comment by darkelement1987** [comment]
I'm not sure about your mr mime config, but you should just add 

`  "login_delay": 25`

to your existing mr mime config
